"""THROWAWAY synthetic case narratives. Verdicts are inputs, not agent decisions."""

CASES = {
    'revenue': {
        'brief': 'Improve page revenue through successive experiments.',
        'events': [
            dict(day=0, kind='select', objective='Find a variant improving revenue per eligible session',
                 evidence='r1: prior baseline retained; variant B tests shorter copy.'),
            dict(day=7, kind='wait', evidence='r2: incomplete window. A: 1000 sessions, 100 clicks, $2000; B: 1000, 160, $1500.',
                 reason='More clicks alone cannot establish a revenue winner; await the planned analysis.'),
            dict(day=14, kind='learn', evidence='r3: fixture analysis rejects B on revenue; B rollback verified.',
                 reason='Shorter copy increased clicks but reduced revenue in this audience.'),
            dict(day=14, kind='select', objective='Evaluate clearer offer details using variant C',
                 evidence='r4: choose a different hypothesis in response to B; retain r3.'),
            dict(day=28, kind='objective_reached', evidence='r5: fixture revenue analysis supports C; rollout receipt C-28 verified.',
                 reason='One supported revenue improvement is live; global optimality is not established.'),
            dict(day=35, kind='wait', evidence='r6: need post-rollout observations before choosing another experiment.',
                 reason='Keep historical trials while waiting for useful new evidence.'),
        ],
    },
    'weekly-product': {
        'brief': 'Improve the product each week using analytics and earlier outcomes.',
        'events': [
            dict(day=0, kind='select', objective='Resolve the onboarding save failure',
                 evidence='p1: 40/100 new users hit save errors; 8/100 search sessions return no results.'),
            dict(day=7, kind='wait', evidence='p2: analytics unavailable; no new counts observed.',
                 reason='A temporary source outage does not establish impossibility.'),
            dict(day=14, kind='objective_reached', evidence='p3: fix deployment verified; reproduction passes; 0/500 subsequent saves error.',
                 reason='Save failure resolved in observed cases; broader product improvement remains open.'),
            dict(day=21, kind='select', objective='Investigate zero-result searches for common terminology',
                 evidence='p4: 45/200 searches return no results; p3 remains part of history.'),
            dict(day=22, kind='objective_impossible', evidence='p4a: the provider exposes no query-ranking internals within permitted access.',
                 reason='This investigation route cannot proceed; other product improvements remain available.'),
            dict(day=22, kind='select', objective='Improve empty-search guidance using observed failed queries',
                 evidence='p4b: local query examples and UI changes are available within scope.'),
            dict(day=28, kind='wait', evidence='p5: proposed search change awaits a representative query sample.',
                 reason='Do not invent an improvement before validating the next hypothesis.'),
        ],
    },
    'feedback': {
        'brief': 'Address requests for a full historical export using the existing read-only integration.',
        'events': [
            dict(day=0, kind='select', objective='Provide a full historical export within the permitted integration',
                 evidence='f1: 3 complaints describe the same missing historical export.'),
            dict(day=3, kind='wait', evidence='f2: provider API temporarily unavailable.',
                 reason='Retry observation later; lack of a response is not proof of lack of capability.'),
            dict(day=7, kind='learn', evidence='f3: fixture API documentation and query both confirm only last 30 days retained.',
                 reason='The requested historical records are absent from the permitted source.'),
            dict(day=8, kind='responsibility_impossible', evidence='f4: no local archive exists; upstream changes and other data sources are outside scope.',
                 reason='Full historical export cannot be produced within the current brief and limits.'),
        ],
    },
    'post-pr-bugs': {
        'brief': 'Observe PR 418 for seven deployed days; investigate and verify fixes for found regressions.',
        'events': [
            dict(day=0, kind='wait', evidence='b1: PR merged; production still runs the previous revision.',
                 reason='Observation of the deployed change has not started.'),
            dict(day=1, kind='select', objective='Observe deployed PR 418 and investigate regressions',
                 evidence='b2: deployment receipt confirms revision pr418; observation ends day 8.'),
            dict(day=3, kind='learn', evidence='b3: new save error reproduced on pr418, absent on previous revision.',
                 reason='Reproduction supports investigating the changed save handling.'),
            dict(day=4, kind='wait', evidence='b4: regression fix passes reproduction locally but is not deployed.',
                 reason='A local passing check does not establish a production fix.'),
            dict(day=5, kind='learn', evidence='b5: deployment receipt fix418 verified; production reproduction passes.',
                 reason='Start observing relevant traffic after the verified fix.'),
            dict(day=8, kind='responsibility_reached', evidence='b6: full observation window; 0 matching errors in 12000 relevant requests after fix.',
                 reason='Bounded observation brief complete with known regression verified resolved.'),
        ],
    },
}
